name: Build SuperShiny Mod

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest  # Requerido para Forge en Windows

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 7.4.2

    - name: Download Pixelmon (dependencia externa)
      run: |
        if (!(Test-Path -Path "libs")) { New-Item -ItemType Directory -Path "libs" }
        Invoke-WebRequest -Uri "https://ejemplo.com/ruta/a/Pixelmon.jar" -OutFile "libs/Pixelmon.jar"  # Reemplaza con tu URL real

    - name: Build with Gradle
      run: ./gradlew build --no-daemon

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: SuperShiny-Mod
        path: |
          build/libs/*.jar
          build/outputs/**/*.jar
